name: ride_along
description: "A Flutter app for students to carpool to school with distance-based fees, powered by Supabase."
publish_to: "none" # Prevents accidental publishing to pub.dev; remove if you plan to publish.

version: 1.0.0+1

environment:
  sdk: ">=3.7.2 <4.0.0" # Updated to ensure compatibility with modern Flutter versions.

dependencies:
  flutter_test: ^11.4.0
  flutter:
    sdk: flutter

  # Core UI and functionality
  cupertino_icons: ^1.0.8 # iOS-style icons for cross-platform consistency
  supabase_flutter: ^2.0.0 # Supabase integration for auth, database, and real-time
  google_maps_flutter: ^2.5.0 # Google Maps for location and route visualization
  geolocator: ^10.0.0 # Access device location for ride tracking
  http: ^1.1.0 # HTTP requests for Google Distance Matrix API or other services
  flutter_stripe: ^11.4.0

dev_dependencies:
    sdk: flutter
  flutter_lints: ^5.0.0 # Recommended lints for code quality

flutter:
  uses-material-design: true # Enables Material Design icons and components


  # Assets section (uncomment and add your assets as needed)
  # assets:
  #   - assets/images/logo.png
  #   - assets/icons/

  # Fonts section (uncomment and configure if custom fonts are needed)
  # fonts:
  #   - family: CustomFont
  #     fonts:
  #       - asset: fonts/CustomFont-Regular.ttf
  #       - asset: fonts/CustomFont-Bold.ttf
  #         weight: 700
